<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>appPARTMENTS: Add Ads</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <#include "Menu.ftlh">
    </div>
</nav>

<!-- Page Content -->
<div class="container main-content about">
    <div class="row">
        <div class="col-lg-12 text-center">
            <img class="us" src="http://kodziaki.jjdd4.is-academy.pl/images/us.png">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 offset-lg-4">
            <div class="row">
                <div class="col-lg-3 text-center">
                    <a href="https://github.com/MikolajA"><i class="fa fa-github fa-2x fa-mikolaj"></i></a>
                    <a href="https://www.linkedin.com/in/mikolaj-andrzejewski"><i class="fa fa-linkedin-square fa-2x fa-mikolaj"></i></a>
                </div>
                <div class="col-lg-3 text-center">
                    <a href="https://github.com/dawid02244"><i class="fa fa-github fa-2x fa-dawid"></i></a>
                    <a href="https://www.linkedin.com/in/dawidmurawski"><i class="fa fa-linkedin-square fa-2x fa-dawid"></i></a>
                </div>
                <div class="col-lg-3 text-center">
                    <a href="https://github.com/P-Pinker"><i class="fa fa-github fa-2x fa-pawel"></i></a>
                    <a href="https://www.linkedin.com/in/pawel-pinker"><i class="fa fa-linkedin-square fa-2x fa-pawel"></i></a>
                </div>
                <div class="col-lg-3 text-center">
                    <a href="https://github.com/martakostyk"><i class="fa fa-github fa-2x fa-marta"></i></a>
                    <a href="https://www.linkedin.com/in/kostyk-marta"><i class="fa fa-linkedin-square fa-2x fa-marta"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /.container -->

<!-- Footer -->
<#include "Footer.ftlh">

<!-- Bootstrap core JavaScript -->

<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>