<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Proudly developed &copy; Kodziaki // infoShare Academy Junior Java Developer - Daily #4 2018</p>
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
    </div>
</footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>