<div class="card">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
        <h4 class="card-title">Tytuł: </h4>
        <h4 class="promoted">POLECANE!</h4>
        <h5 class="city">Miasto: , Dzielnica: </h5>
        <p class="card-text">Opis: <i>Tutaj automatycznie powinno wczytać się X pierwszych znaków z opisu...</i></p>
    </div>
    <div class="card-footer">
        <a href="id" class="btn btn-primary">Zobacz</a>
    </div>
</div>