<div class="card">
    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
    <div class="card-body">
        <h4 class="card-title">Mieszkanie nowe</h4>
        <h5 class=""city">Miasto, dzielnica</h5>
        <p class="card-text">Tutaj automatycznie zassa się X pierwszych znaków z opisu...</p>
    </div>
    <div class="card-footer">
        <a href="#" class="btn btn-primary">Zobacz</a>
    </div>
</div>