FROM jboss/wildfly

MAINTAINER "infoShare Academy kodziaki"

COPY target/appPartments.war /opt/wildfly/standalone/deployments/
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
